### ISSUE TITLE
Enhancement Request - searches by byline

### ISSUE THREAD

**Issue by pssguy** [toledobastos/GuardianR#4]
I do not believe this is currently available but could be obtained. Correct me if I am wrong

I would like to get articles limited to those by byline (e.g.  Hugh Muir) which is a variable in the returned data.frame

Thanks

**Comment by toledobastos** [comment]
I'll see if I can add that.

**Comment by pssguy** [comment]
Thanks. Definitely plan to use the package in an app

**Comment by mkjohnman** [comment]
Had a look at implementing this - don't think you can directly filter the API by the byline ([Guardian API Explorer](http://open-platform.theguardian.com/explore/) didn’t seem to have any filters for it). Your best bet’s probably to download the articles over the period you want then filter the data frame by the byline field. If they add this type of filtering in the future, will definitely add it in to the package. :)

**Comment by mkjohnman** [comment]
If they add this type of filtering in the future, will definitely add it in to the package.
